### ISSUE TITLE
Avoid failing when the gem upload fails e.g. due to version duplication

### ISSUE THREAD

**Issue by qnm** [jstastny/publish-gem-to-github#1]
Just something perhaps to add to the README.

I'm in the situation where I wish to push the gem every commit to master, and be okay if it already exists. There's a directive in Github Actions that helps achieve this: `continue-on-error: true` e.g.

```
      - name: Build and publish gem
        continue-on-error: true
        uses: jstastny/publish-gem-to-github@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: jstastny
```
